sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"

install: mvn --settings .settings.xml clean install

## Using packageCloud
deploy:
  provider: script
  script: "cp .settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
